# .github/workflows/main.yml
# Copy/pasted from https://angular.io/guide/testing#configure-project-for-github-actions
name: CI app through Github Actions
on: push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Setup
        run: npm ci

      - name: Test
        working-directory: ./
        run: npm test
